# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: voltha
spec:
  clusterIP: None
  selector:
    app: fluentd
  ports:
  - protocol: TCP
    port: 24224
    targetPort: 24224
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fluentd
  namespace: voltha
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fluentd
      annotations:
        cni: "calico"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: fluentd
        image: fluent/fluentd:v0.12.42
        volumeMounts:
        - name: fluentd-log
          mountPath: /fluentd/log
        ports:
        - containerPort: 24224
      volumes:
      - name: fluentd-log
        hostPath:
          path: /tmp/fluentd
          type: Directory

