# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Ensure Swarm Master Initialization
  command: "docker swarm init --advertise-addr {{ swarm_master_addr }}"
  when: target == "swarm-master"
  tags: [swarm]

- name: Capture Swarm Cluster Manager Token
  become: voltha
  shell: ssh -i /home/voltha/.keys/{{ swarm_master_addr }} voltha@{{ swarm_master_addr }} sudo docker swarm join-token -q manager 2>/dev/null
  register: manager_token
  changed_when: false
  when: target == "swarm-master-backup"
  tags: [swarm]

- name: Debug
  debug:
    msg: "TOKEN: {{ manager_token.stdout }}"
  when: target == "swarm-master-backup"
  tags: [swarm]

- name: Join Swarm Cluster
  command: "docker swarm join --token {{ manager_token.stdout }} {{ swarm_master_addr }}:2377"
  when: target == "swarm-master-backup"
  tags: [swarm]
